### ISSUE TITLE
对vue2的支持可能出现了BUG, 无论是切换2.7.14或者2.6.14页面都报错了

### ISSUE THREAD

**Issue by codelzb** [opentiny/tiny-vue-playground#21]
https://opentiny.github.io/tiny-vue-playground/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgICA8YnV0dG9uIDpjbGFzcz1cIlsneGwtYnV0dG9uJywgdHlwZSA/ICd4bC1idXR0b24tLScgKyB0eXBlIDogJyddXCI+XG4gICAge3sgbnVtIHwgY2FwaXRhbGl6ZSB9fVxuICA8L2J1dHRvbj5cblxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdD5cbmV4cG9ydCBkZWZhdWx0IHtcbiAgbmFtZTogXCJYbEJ1dHRvblwiLFxuICBkYXRhKCl7XG4gICAgcmV0dXJue1xuICAgICAgICBudW06JzEnLFxuICAgIH1cbiAgfSxcbiAgcHJvcHM6IHtcbiAgICB0eXBlOiB7IHR5cGU6IFN0cmluZywgZGVmYXVsdDogJ2RlZmF1bHQnIH1cbiAgfSxcbiAgZmlsdGVyczp7XG4gICAgY2FwaXRhbGl6ZTogZnVuY3Rpb24gKHZhbHVlKSB7XG4gICAgICAgIHJldHVybiA5OTlcbiAgICB9XG4gIH1cbn1cbjwvc2NyaXB0PiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMi43XG4gIH1cbn1cbiIsIl9vIjp7fX0=
![image](https://github.com/opentiny/tiny-vue-playground/assets/64744556/cc6ad704-6210-4daa-aa43-63d15368de66)

**Comment by codelzb** [comment]
@mengqiuleo 如果切换vue3会是正常的, 只是vue3对filters选项不再支持

**Comment by mengqiuleo** [comment]
@codelzb 你再试一下，我vue2这边是可以正常显示的，或者提供一下你的vue版本号
![Snipaste_2023-08-13_20-55-41](https://github.com/opentiny/tiny-vue-playground/assets/85825776/390b38d5-b6bb-4e01-844c-8741b55b4497)

**Comment by codelzb** [comment]
> @codelzb 你再试一下，我vue2这边是可以正常显示的，或者提供一下你的vue版本号 ![Snipaste_2023-08-13_20-55-41](https://user-images.githubusercontent.com/85825776/260304211-390b38d5-b6bb-4e01-844c-8741b55b4497.jpg)

sor, 我忘记了TinyVue也要改成2.X版本
